### ISSUE TITLE
SEO Bundle - Error with too long description

### ISSUE THREAD

**Issue by sabinecimaponti** [Novactive/Nova-eZPlatform-Bundles#25]
**Bundle(s) affected**: novactive/ezseobundle

**Description**  
When a too long description is added, a 500 is generated with a database error

**How to reproduce**  
Edit a content on eZ admin interface and add a long text on the seo nova description field

**Possible Solution**  
Add check on string length

**Additional context**  

<img width="960" alt="error-ez-nova-seao-bundle" src="https://user-images.githubusercontent.com/8794068/106587803-5d2abf80-654a-11eb-85f9-47de26745e4a.png">

**Comment by Plopix** [comment]
hello @sabinecimaponti 
This is odd. How big of a text did you put?
There is a way to enforce a limitation already

```            fieldtype_metas:
                title:
                    label: 'Title'
                    default_pattern: "<title|name>"
                description:
                    label: 'Description'
                    default_pattern: "<description|short_description|title|name>"
                    minLength: 5
                    maxLength: 25
                keywords:
                    label: 'Keywords'
                    default_pattern: ~

```

In the DB the type is `text`, but we don't put any limitation by default.
