### ISSUE TITLE
Preview of new translation leads to error

### ISSUE THREAD

**Issue by homarx** [Novactive/Nova-eZPlatform-Bundles#31]
ezsystems/ezpublish-kernel                      v7.5.16
novactive/ezseobundle                           4.2.0 

When creating a new translation of content with seometas-field preview shows error.
When navigating back this message appears:

An exception has been thrown during the rendering of a template ("Could not find 'Content' with identifier 'array ( 'id' => 426, 'languages' => array ( 0 => 'eng-GB', ), 'versionNo' => NULL, )'") in "NovaeZSEOBundle:fields:novaseometas.html.twig". [in vendor/twig/twig/src/Template.php:196]

I think content can't be loaded in function computeMetas of bundle/Twig/NovaeZSEOExtension.php.

Could fix it by changing code to:

```
       try{
            $content      = $this->eZRepository->getContentService()->loadContentByContentInfo($contentInfo, $languages);
        } catch(NotFoundException | UnauthorizedException $e){
            return '';
        }
```

**Comment by Plopix** [comment]
you fixed that code in PR @homarx right? Can you please close that ticket? Thanks again!

**Comment by homarx** [comment]
> you fixed that code in PR @homarx right? Can you please close that ticket? Thanks again!

That's right!
