### ISSUE TITLE
Backend features "Import Urls" and "History Import Urls" not working

### ISSUE THREAD

**Issue by homarx** [Novactive/Nova-eZPlatform-Bundles#44]
novactive/ezseobundle                          v5.5.0
Ibexa 3.3.6

**Description**  
Backend features "Import Urls" and "History Import Urls" not working.
The following error is thrown when trying to use them:

Attempted to load class "ArrayCache" from namespace "Doctrine\Common\Cache". Did you forget a "use" statement for another namespace? [in vendor/novactive/ezseobundle/bundle/Core/SiteAccessAwareEntityManagerFactory.php:76]

**How to reproduce**  
In ibexa backend click on menu item "SEO" > "Import Urls" or "SEO" > "History Import Urls"

**Comment by Plopix** [comment]
It sounds like a dependency on Doctrine something issue.

**Comment by homarx** [comment]
I have created a pull request on this:
https://github.com/Novactive/Nova-eZPlatform-Bundles/pull/49

**Comment by Plopix** [comment]
merged and tagged, you want to switch to `v6` I did not backported it
