### ISSUE TITLE
Avoid death star version constraint

### ISSUE THREAD

**Issue by scheb** [Novactive/Nova-eZPlatform-Bundles#47]
**Bundle(s) related**: 2FABundle

Hello there, I've seen your tweet that you have integrated my 2fa-bundle, great work!

One thing that caught my eye, you're referencing dependencies (and 2fa-bundle) with a [death star version constraint](https://thephp.cc/articles/the-death-star-version-constraint) and I'm wondering if that's intentional.

https://github.com/Novactive/Nova-eZPlatform-Bundles/blob/c29d516604b74a1ade7d7b96e2638ff7abab02a4/components/2FABundle/composer.json#L30-L32

With that version constraint you'd accept "any version" (including development branches) and I can already tell you that 2fa-bundle version 6 will definitely introduce some breaking changes. The better solution in my opinion would be a `^5.0` constraint. Except you have good reasons to use `*`. Might be that dependencies are managed differently in the EZ ecosystem.

Btw.: I'd recommend not using `scheb/2fa`, but `scheb/2fa-bundle` instead. `scheb/2fa` is the all-in-one package which likely contains many dependencies that you don't need. And `scheb/2fa` includes `scheb/2fa-google-authenticator`, so there's actually no need to require that package when `scheb/2fa` is required.

Hope that helps!

**Comment by Plopix** [comment]
hey, @scheb we are really honored by your review! We will fix this right away!

**Comment by maximstrukov** [comment]
https://github.com/Novactive/Nova-eZPlatform-Bundles/pull/48

**Comment by Plopix** [comment]
Merged and tagged
